import Link from 'next/link';
import { Navbar } from '@/components/ui/navbar';
import { Footer } from '@/components/ui/footer';
import { FileText, ArrowLeft, AlertTriangle } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — VoxDesk',
  description: 'Terms of Service and Usage Disclosures for VoxDesk Voice Operations Platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#F8FAFC] text-[#0F172A]">
      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto p-6 py-12 space-y-8">
        <div className="space-y-3">
          <Link
            href="/"
            className="text-xs text-[#64748B] hover:text-[#0F172A] flex items-center gap-1 transition-colors mb-4"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Return to Home
          </Link>
          <div className="flex items-center gap-2 text-[#1D4ED8]">
            <FileText className="w-5 h-5" />
            <span className="text-xs font-semibold uppercase tracking-wider">
              Terms & Conditions
            </span>
          </div>
          <h1 className="text-3xl font-extrabold text-[#0F172A] tracking-tight">
            VoxDesk Terms of Service
          </h1>
          <p className="text-xs font-mono text-[#64748B]">
            Effective Date: August 3, 2026 • Environment: Interactive Platform Demo
          </p>
        </div>

        {/* Disclaimer Notice */}
        <div className="p-4 rounded-lg bg-white border border-[#CBD5E1] text-xs space-y-2 text-[#334155] shadow-sm">
          <div className="flex items-center gap-2 font-bold text-[#B45309]">
            <AlertTriangle className="w-4 h-4" />
            <span>No Legal Advice & Fictional Business Notice</span>
          </div>
          <p className="leading-relaxed">
            VoxDesk is a voice operations software demonstration. Conversational content,
            consultation bookings, and lead scores generated by this system do not constitute
            binding legal representation or medical advice.
          </p>
        </div>

        <div className="space-y-6 text-xs text-[#334155] leading-relaxed">
          <section className="space-y-2 bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-sm">
            <h2 className="text-sm font-bold text-[#0F172A]">
              1. Demonstration Scope & Usage Limits
            </h2>
            <p>
              The public voice sandbox is provided for technology evaluation under operational
              session limits.
            </p>
          </section>

          <section className="space-y-2 bg-white p-6 rounded-xl border border-[#E2E8F0] shadow-sm">
            <h2 className="text-sm font-bold text-[#0F172A]">
              2. Intellectual Property & Ownership
            </h2>
            <p>
              VoxDesk and its underlying voice operations architecture are owned by Arslan Vuzmal
              Lone.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
