import Link from "next/link";
import { Navbar } from "@/components/ui/navbar";
import { FileText, ArrowLeft, AlertTriangle } from "lucide-react";

export const metadata = {
  title: "Terms of Service — VoxDesk AI",
  description:
    "Terms of Service and Usage Disclosures for the VoxDesk AI platform demonstration.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-[#0B0D10] text-[#F4F4F5]">
      <Navbar />

      <main className="flex-1 max-w-4xl w-full mx-auto p-6 py-12 space-y-8">
        <div className="space-y-3">
          <Link
            href="/"
            className="text-xs text-[#8B949E] hover:text-white flex items-center gap-1 transition-colors mb-4"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Return to Home
          </Link>
          <div className="flex items-center gap-2 text-[#2DD4BF]">
            <FileText className="w-5 h-5" />
            <span className="text-xs font-mono font-bold uppercase tracking-wider">
              Terms & Conditions
            </span>
          </div>
          <h1 className="text-3xl font-extrabold text-white tracking-tight">
            VoxDesk AI Terms of Service
          </h1>
          <p className="text-xs font-mono text-[#8B949E]">
            Effective Date: August 3, 2026 • Environment: Public Portfolio Demo
          </p>
        </div>

        {/* Disclaimer Notice */}
        <div className="p-4 rounded-lg bg-[#171C22] border border-[#272D35] text-xs space-y-2 text-[#D4D4D8]">
          <div className="flex items-center gap-2 font-bold text-amber-400">
            <AlertTriangle className="w-4 h-4" />
            <span>No Legal Advice & Fictional Business Notice</span>
          </div>
          <p className="leading-relaxed">
            VoxDesk AI is a software demonstration of AI voice receptionist
            technology. The conversational content, business scenarios,
            consultation bookings, and lead scores generated by this system do
            not constitute legal advice or formal legal representation.
          </p>
        </div>

        <div className="space-y-8 text-xs text-[#D4D4D8] leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-white tracking-tight">
              1. Demonstration Scope & Usage Limits
            </h2>
            <p>
              The public voice sandbox is subject to strict cost controls and
              usage rate limits:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-[#8B949E]">
              <li>
                Maximum 3 demo sessions per IP address per 24-hour period.
              </li>
              <li>
                Maximum 6 conversational turns and 3 minutes per call session.
              </li>
              <li>
                600 maximum input characters per turn and 350 output characters
                per response.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-white tracking-tight">
              2. Prohibited Conduct & Fair Use
            </h2>
            <p>
              Users agree not to attempt automated scraping, quota
              circumvention, injection attacks, reverse engineering, or
              submission of harmful or unlawful content through the voice or
              text consoles. VoxDesk AI reserves the right to terminate active
              sessions violating these terms.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-white tracking-tight">
              3. Service Availability & Fallback Architecture
            </h2>
            <p>
              While VoxDesk AI strives for 99.9% uptime, public voice services
              rely on external LLM and speech synthesis APIs. In the event of
              upstream provider maintenance, VoxDesk AI automatically employs
              deterministic scenario fallbacks to ensure continuous
              demonstration availability.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-white tracking-tight">
              4. Intellectual Property & Ownership
            </h2>
            <p>
              All software source code, repository architectures, visual design
              systems, and documentation are authored and owned by{" "}
              <strong className="text-white">Arslan Vuzmal Lone</strong>.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
